#!/usr/bin/env python3
"""
optimize_astro_site.py

Scaffolds the astro/ static HTML tutorial site to match Ray's standard course
layout (cf. course_template, python_intro):

  - Generates a shared stylesheet (styles/styles.css) with CSS custom properties
    for light/dark theming.
  - Generates js/theme.js (toggle + persisted preference + system default).
  - Generates js/nav.js (prev/next navigation, page order edited by hand).
  - Injects a sticky header into every HTML page with:
      [ Site title ] ............ [ Ray's House of Fun | 🌙 ]
  - Wires up the shared stylesheet and scripts in every page <head>.
  - Adds a <nav id="page-nav"> placeholder at the bottom of <main>.

Idempotent: re-running only touches files that actually need to change. A
`<meta name="scaffold-version">` tag in each processed page records the version
so future runs can detect and upgrade in place.

Usage:
    python3 optimize_astro_site.py                    # operate on cwd
    python3 optimize_astro_site.py --project-root .   # explicit
    python3 optimize_astro_site.py --dry-run          # show changes only
    python3 optimize_astro_site.py --no-backup        # skip .bak files

Dependencies:
    pip install beautifulsoup4
"""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

try:
    from bs4 import BeautifulSoup
except ImportError:
    sys.stderr.write(
        "Missing dependency: beautifulsoup4.\n"
        "Install with:  pip install beautifulsoup4\n"
    )
    sys.exit(1)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

SCAFFOLD_VERSION = "1"
SCAFFOLD_META_NAME = "scaffold-version"

HUB_URL = "https://rays-home.netlify.app"
HUB_LABEL = "Ray's House of Fun"
SITE_TITLE = "Astro & Starlight Course"

STYLES_DIR = "styles"
JS_DIR = "js"
CSS_REL = f"{STYLES_DIR}/styles.css"
THEME_JS_REL = f"{JS_DIR}/theme.js"
NAV_JS_REL = f"{JS_DIR}/nav.js"

# Files we never touch even if they end in .html
SKIP_NAMES = {"404.html"}


# ---------------------------------------------------------------------------
# Asset templates
# ---------------------------------------------------------------------------

CSS_CONTENT = """/* =========================================================
 * Astro & Starlight Course — shared stylesheet
 * Generated by optimize_astro_site.py (scaffold v%s)
 * Light/dark theme controlled by [data-theme] on <html>.
 * ========================================================= */

:root {
  --bg:           #ffffff;
  --bg-alt:       #f5f5f7;
  --surface:      #ffffff;
  --border:       #e4e4e7;
  --text:         #18181b;
  --text-muted:   #52525b;
  --accent:       #6b46c1;
  --accent-hover: #553c9a;
  --code-bg:      #f4f4f5;
  --code-text:    #18181b;
  --shadow:       0 1px 3px rgba(0, 0, 0, 0.08);
  --radius:       8px;
  --maxw:         960px;
  --font-sans:    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                  Helvetica, Arial, sans-serif;
  --font-mono:    ui-monospace, SFMono-Regular, "SF Mono", Consolas,
                  "Liberation Mono", Menlo, monospace;
}

[data-theme="dark"] {
  --bg:           #0f0f10;
  --bg-alt:       #1a1a1c;
  --surface:      #18181b;
  --border:       #2a2a2e;
  --text:         #f4f4f5;
  --text-muted:   #a1a1aa;
  --accent:       #a78bfa;
  --accent-hover: #c4b5fd;
  --code-bg:      #1f1f23;
  --code-text:    #f4f4f5;
  --shadow:       0 1px 3px rgba(0, 0, 0, 0.4);
}

* { box-sizing: border-box; }

html { scroll-behavior: smooth; }

body {
  margin: 0;
  font-family: var(--font-sans);
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  transition: background 0.2s ease, color 0.2s ease;
}

/* --- Header ----------------------------------------------- */
.site-header {
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  position: sticky;
  top: 0;
  z-index: 10;
  box-shadow: var(--shadow);
}

.site-header__inner {
  max-width: var(--maxw);
  margin: 0 auto;
  padding: 0.75rem 1rem;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1rem;
}

.site-header__title {
  font-weight: 600;
  font-size: 1.05rem;
  color: var(--text);
  text-decoration: none;
}

.site-header__title:hover { color: var(--accent); }

.site-header__nav {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.site-header__hub-link {
  color: var(--accent);
  text-decoration: none;
  font-weight: 500;
  font-size: 0.95rem;
}

.site-header__hub-link:hover {
  color: var(--accent-hover);
  text-decoration: underline;
}

.theme-toggle {
  background: transparent;
  border: 1px solid var(--border);
  color: var(--text);
  padding: 0.35rem 0.6rem;
  border-radius: var(--radius);
  cursor: pointer;
  font-size: 1rem;
  line-height: 1;
  transition: background 0.15s ease, border-color 0.15s ease;
}

.theme-toggle:hover {
  background: var(--bg-alt);
  border-color: var(--accent);
}

/* --- Main content ----------------------------------------- */
main {
  max-width: var(--maxw);
  margin: 0 auto;
  padding: 2rem 1rem 3rem;
}

h1, h2, h3, h4 { line-height: 1.25; color: var(--text); }
h1 { font-size: 2rem;   margin-top: 0; }
h2 { font-size: 1.5rem; margin-top: 2rem; }
h3 { font-size: 1.2rem; margin-top: 1.5rem; }

p { margin: 1rem 0; }

a { color: var(--accent); }
a:hover { color: var(--accent-hover); }

code {
  font-family: var(--font-mono);
  background: var(--code-bg);
  color: var(--code-text);
  padding: 0.15rem 0.35rem;
  border-radius: 4px;
  font-size: 0.9em;
}

pre {
  background: var(--code-bg);
  color: var(--code-text);
  padding: 1rem;
  border-radius: var(--radius);
  overflow-x: auto;
  border: 1px solid var(--border);
}

pre code {
  background: transparent;
  padding: 0;
  font-size: 0.9em;
}

blockquote {
  border-left: 4px solid var(--accent);
  background: var(--bg-alt);
  margin: 1.5rem 0;
  padding: 0.75rem 1rem;
  color: var(--text-muted);
  border-radius: 0 var(--radius) var(--radius) 0;
}

table {
  border-collapse: collapse;
  width: 100%%;
  margin: 1rem 0;
}

th, td {
  border: 1px solid var(--border);
  padding: 0.5rem 0.75rem;
  text-align: left;
}

th { background: var(--bg-alt); }

img { max-width: 100%%; height: auto; border-radius: var(--radius); }

/* --- Prev/Next nav ---------------------------------------- */
.page-nav {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
  margin-top: 3rem;
  padding-top: 1.5rem;
  border-top: 1px solid var(--border);
}

.page-nav a {
  display: inline-block;
  padding: 0.6rem 1rem;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  text-decoration: none;
  color: var(--text);
  font-weight: 500;
  transition: border-color 0.15s ease, color 0.15s ease;
}

.page-nav a:hover {
  border-color: var(--accent);
  color: var(--accent);
}

.page-nav__spacer { flex: 1; }

/* --- Mobile ----------------------------------------------- */
@media (max-width: 600px) {
  .site-header__inner { flex-wrap: wrap; }
  .site-header__nav   { gap: 0.6rem; }
  h1                  { font-size: 1.6rem; }
}
""" % SCAFFOLD_VERSION


THEME_JS_CONTENT = """/* theme.js — light/dark toggle, persisted in localStorage.
 * Reads system preference if no saved value. Applies before paint
 * by running synchronously from <head>.
 */
(function () {
  var STORAGE_KEY = 'astro-course-theme';
  var saved = null;
  try { saved = localStorage.getItem(STORAGE_KEY); } catch (e) {}
  var prefersDark = window.matchMedia &&
                    window.matchMedia('(prefers-color-scheme: dark)').matches;
  var initial = saved || (prefersDark ? 'dark' : 'light');
  document.documentElement.setAttribute('data-theme', initial);

  function icon(theme) { return theme === 'dark' ? '\\u2600\\ufe0f' : '\\ud83c\\udf19'; }
  function label(theme) {
    return 'Switch to ' + (theme === 'dark' ? 'light' : 'dark') + ' mode';
  }

  document.addEventListener('DOMContentLoaded', function () {
    var btn = document.getElementById('theme-toggle');
    if (!btn) return;
    var current = document.documentElement.getAttribute('data-theme');
    btn.textContent = icon(current);
    btn.setAttribute('aria-label', label(current));

    btn.addEventListener('click', function () {
      var now = document.documentElement.getAttribute('data-theme');
      var next = now === 'dark' ? 'light' : 'dark';
      document.documentElement.setAttribute('data-theme', next);
      try { localStorage.setItem(STORAGE_KEY, next); } catch (e) {}
      btn.textContent = icon(next);
      btn.setAttribute('aria-label', label(next));
    });
  });
})();
"""


NAV_JS_CONTENT = """/* nav.js — prev/next page navigation.
 *
 * Add your pages to PAGES below in the order learners should read them.
 * Pages NOT listed in PAGES still render; they just won't show prev/next.
 *
 * Each entry: { href: 'filename.html', title: 'Lesson Title' }
 */
(function () {
  var PAGES = [
    // { href: 'index.html',   title: 'Home' },
    // { href: 'lesson-01.html', title: 'Lesson 1: Intro to Astro' },
    // { href: 'lesson-02.html', title: 'Lesson 2: Components & Layouts' },
    // ...
  ];

  function currentHref() {
    var parts = window.location.pathname.split('/');
    var leaf = parts[parts.length - 1];
    return leaf || 'index.html';
  }

  document.addEventListener('DOMContentLoaded', function () {
    var container = document.getElementById('page-nav');
    if (!container || PAGES.length === 0) return;

    var here = currentHref();
    var idx = -1;
    for (var i = 0; i < PAGES.length; i++) {
      if (PAGES[i].href === here) { idx = i; break; }
    }
    if (idx === -1) return;

    container.innerHTML = '';

    if (idx > 0) {
      var prev = PAGES[idx - 1];
      var a = document.createElement('a');
      a.href = prev.href;
      a.textContent = '\\u2190 ' + prev.title;
      container.appendChild(a);
    } else {
      var sp = document.createElement('span');
      sp.className = 'page-nav__spacer';
      container.appendChild(sp);
    }

    if (idx < PAGES.length - 1) {
      var next = PAGES[idx + 1];
      var b = document.createElement('a');
      b.href = next.href;
      b.textContent = next.title + ' \\u2192';
      container.appendChild(b);
    } else {
      var sp2 = document.createElement('span');
      sp2.className = 'page-nav__spacer';
      container.appendChild(sp2);
    }
  });
})();
"""


# ---------------------------------------------------------------------------
# HTML helpers
# ---------------------------------------------------------------------------

def header_markup():
    return (
        '<header class="site-header" data-scaffold="header">\n'
        '  <div class="site-header__inner">\n'
        f'    <a href="index.html" class="site-header__title">{SITE_TITLE}</a>\n'
        '    <nav class="site-header__nav">\n'
        f'      <a href="{HUB_URL}" class="site-header__hub-link">{HUB_LABEL}</a>\n'
        '      <button id="theme-toggle" class="theme-toggle" type="button" '
        'aria-label="Toggle theme">🌙</button>\n'
        '    </nav>\n'
        '  </div>\n'
        '</header>'
    )


def page_nav_markup():
    return '<nav class="page-nav" id="page-nav" data-scaffold="page-nav"></nav>'


def rel_path(html_file: Path, asset_path: Path) -> str:
    rel = os.path.relpath(asset_path, html_file.parent)
    return rel.replace(os.sep, "/")


def ensure_head(soup: BeautifulSoup):
    head = soup.find("head")
    if head is not None:
        return head
    html = soup.find("html")
    if html is None:
        html = soup.new_tag("html")
        for child in list(soup.children):
            html.append(child.extract())
        soup.append(html)
    head = soup.new_tag("head")
    html.insert(0, head)
    return head


def ensure_body(soup: BeautifulSoup):
    body = soup.find("body")
    if body is not None:
        return body
    html = soup.find("html") or soup
    body = soup.new_tag("body")
    html.append(body)
    return body


def ensure_link(soup, head, href: str) -> bool:
    for link in head.find_all("link"):
        if link.get("href") == href and "stylesheet" in (link.get("rel") or []):
            return False
    tag = soup.new_tag("link", rel="stylesheet", href=href)
    head.append(tag)
    return True


def ensure_script(soup, head, src: str, defer: bool = True) -> bool:
    for script in head.find_all("script"):
        if script.get("src") == src:
            if defer and not script.has_attr("defer"):
                script["defer"] = ""
                return True
            return False
    tag = soup.new_tag("script", src=src)
    if defer:
        tag["defer"] = ""
    head.append(tag)
    return True


def replace_or_insert_header(soup, body) -> bool:
    new_header = BeautifulSoup(header_markup(), "html.parser").find("header")
    existing = body.find("header", attrs={"data-scaffold": "header"})
    if existing:
        if str(existing) == str(new_header):
            return False
        existing.replace_with(new_header)
        return True
    body.insert(0, new_header)
    return True


def ensure_page_nav(soup, body) -> bool:
    existing = body.find("nav", attrs={"data-scaffold": "page-nav"})
    if existing:
        return False
    new_nav = BeautifulSoup(page_nav_markup(), "html.parser").find("nav")
    main = body.find("main")
    (main or body).append(new_nav)
    return True


def mark_scaffolded(soup, head) -> bool:
    existing = head.find("meta", attrs={"name": SCAFFOLD_META_NAME})
    if existing:
        if existing.get("content") == SCAFFOLD_VERSION:
            return False
        existing["content"] = SCAFFOLD_VERSION
        return True
    meta = soup.new_tag("meta")
    meta.attrs["name"] = SCAFFOLD_META_NAME
    meta.attrs["content"] = SCAFFOLD_VERSION
    head.append(meta)
    return True


# ---------------------------------------------------------------------------
# File operations
# ---------------------------------------------------------------------------

def write_if_changed(path: Path, content: str, backup: bool, dry_run: bool) -> str:
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return "unchanged"
        if not dry_run:
            if backup:
                shutil.copy2(path, path.with_suffix(path.suffix + ".bak"))
            path.write_text(content, encoding="utf-8")
        return "updated"
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return "created"


def process_html_file(path: Path, project_root: Path,
                      backup: bool, dry_run: bool):
    notes: list[str] = []
    try:
        raw = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return "skipped", [f"could not decode {path.name} as UTF-8"]

    soup = BeautifulSoup(raw, "html.parser")

    head = ensure_head(soup)
    body = ensure_body(soup)

    css_rel = rel_path(path, project_root / CSS_REL)
    theme_js_rel = rel_path(path, project_root / THEME_JS_REL)
    nav_js_rel = rel_path(path, project_root / NAV_JS_REL)

    ensure_link(soup, head, css_rel)
    ensure_script(soup, head, theme_js_rel, defer=True)
    ensure_script(soup, head, nav_js_rel, defer=True)
    replace_or_insert_header(soup, body)
    ensure_page_nav(soup, body)
    mark_scaffolded(soup, head)

    inline_styles = soup.find_all("style")
    if inline_styles:
        notes.append(f"{len(inline_styles)} inline <style> block(s) preserved "
                     f"(may conflict with shared stylesheet)")

    new_content = str(soup)
    if new_content == raw:
        return "unchanged", notes

    if not dry_run:
        if backup:
            shutil.copy2(path, path.with_suffix(path.suffix + ".bak"))
        path.write_text(new_content, encoding="utf-8")
    return "updated", notes


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def discover_html(project_root: Path) -> list[Path]:
    found: list[Path] = []
    for path in sorted(project_root.rglob("*.html")):
        rel = path.relative_to(project_root)
        if any(part in {"styles", "js", "assets", "node_modules", ".git", "_backup"}
               for part in rel.parts):
            continue
        if path.name in SKIP_NAMES:
            continue
        found.append(path)
    return found


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Scaffold the astro/ HTML tutorial site "
                    "(shared CSS, dark/light toggle, header, prev/next)."
    )
    parser.add_argument("--project-root", type=Path, default=Path.cwd())
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--no-backup", action="store_true")
    args = parser.parse_args()

    project_root = args.project_root.resolve()
    backup = not args.no_backup
    dry_run = args.dry_run

    if not project_root.is_dir():
        sys.stderr.write(f"Not a directory: {project_root}\n")
        return 2

    mode = "DRY-RUN" if dry_run else "APPLY"
    print(f"\n=== optimize_astro_site.py  [{mode}] ===")
    print(f"Project root:  {project_root}")
    print(f"Backups:       {'on (.bak)' if backup else 'off'}")
    print(f"Scaffold ver:  {SCAFFOLD_VERSION}\n")

    print("Assets:")
    asset_results = {
        CSS_REL:      write_if_changed(project_root / CSS_REL,
                                       CSS_CONTENT, backup, dry_run),
        THEME_JS_REL: write_if_changed(project_root / THEME_JS_REL,
                                       THEME_JS_CONTENT, backup, dry_run),
        NAV_JS_REL:   write_if_changed(project_root / NAV_JS_REL,
                                       NAV_JS_CONTENT, backup, dry_run),
    }
    for rel, status in asset_results.items():
        print(f"  [{status:9s}] {rel}")

    html_files = discover_html(project_root)
    print(f"\nHTML files ({len(html_files)} found):")
    if not html_files:
        print("  (none — nothing to scaffold)")

    counts = {"updated": 0, "unchanged": 0, "skipped": 0}
    all_notes: list[tuple[str, str]] = []

    for path in html_files:
        rel = path.relative_to(project_root)
        status, notes = process_html_file(path, project_root, backup, dry_run)
        counts[status] = counts.get(status, 0) + 1
        print(f"  [{status:9s}] {rel}")
        for n in notes:
            all_notes.append((str(rel), n))

    print("\nSummary:")
    print(f"  Assets:   "
          f"{sum(1 for s in asset_results.values() if s == 'created'):>3} created, "
          f"{sum(1 for s in asset_results.values() if s == 'updated'):>3} updated, "
          f"{sum(1 for s in asset_results.values() if s == 'unchanged'):>3} unchanged")
    print(f"  HTML:     "
          f"{counts.get('updated', 0):>3} updated, "
          f"{counts.get('unchanged', 0):>3} unchanged, "
          f"{counts.get('skipped', 0):>3} skipped")

    if all_notes:
        print("\nNotes:")
        for file_rel, note in all_notes:
            print(f"  · {file_rel}: {note}")

    if dry_run:
        print("\n(dry-run — no files were written)")
    else:
        print("\nNext step: open js/nav.js and fill in the PAGES array "
              "with your lesson order.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
